version: '3'

services:

  helpdesk:
    container_name: dataview
    restart: always
    build: ../'Projeto dataview'
    ports:
      - "8001:8001"
    command: gunicorn -b 0.0.0.0 --workers=4  --threads=3 app:'create_app()' --preload

