"""empty message

Revision ID: 03c8fa745c8f
Revises: 5f1a2bd186d7
Create Date: 2023-09-21 11:35:47.068400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03c8fa745c8f'
down_revision = '5f1a2bd186d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('p_defined', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_column('p_defined')

    # ### end Alembic commands ###
