"""empty message

Revision ID: 05884d22f5af
Revises: ab10a47afb4e
Create Date: 2024-06-03 11:12:23.197096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05884d22f5af'
down_revision = 'ab10a47afb4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dados', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome_tabela', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dados', schema=None) as batch_op:
        batch_op.drop_column('nome_tabela')

    # ### end Alembic commands ###
