"""empty message

Revision ID: 2b66bbf3ccf6
Revises: ddbb10bd2547
Create Date: 2024-06-03 10:24:54.427093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b66bbf3ccf6'
down_revision = 'ddbb10bd2547'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('filtro', schema=None) as batch_op:
        batch_op.alter_column('_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('filtro', schema=None) as batch_op:
        batch_op.alter_column('_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
