"""empty message

Revision ID: 30374c9cc0a3
Revises: 05884d22f5af
Create Date: 2024-06-06 14:42:37.461557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30374c9cc0a3'
down_revision = '05884d22f5af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lista_colunas',
    sa.Column('_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tabela', sa.String(), nullable=False),
    sa.Column('colunas', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_table('perfil',
    sa.Column('_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('create_filter', sa.Boolean(), nullable=True),
    sa.Column('create_dados', sa.Boolean(), nullable=True),
    sa.Column('view_users', sa.Boolean(), nullable=True),
    sa.Column('create_perfil', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('_id')
    )
    with op.batch_alter_table('filtro', schema=None) as batch_op:
        batch_op.add_column(sa.Column('perfis', sa.String(), nullable=False))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('perfil', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('perfil')

    with op.batch_alter_table('filtro', schema=None) as batch_op:
        batch_op.drop_column('perfis')

    op.drop_table('perfil')
    op.drop_table('lista_colunas')
    # ### end Alembic commands ###
