"""empty message

Revision ID: 482158bff1ad
Revises: 725af78da855
Create Date: 2024-05-20 11:50:11.599393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '482158bff1ad'
down_revision = '725af78da855'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('filtro', schema=None) as batch_op:
        batch_op.alter_column('_id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('_id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('filtro', schema=None) as batch_op:
        batch_op.alter_column('_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###
