"""empty message

Revision ID: 72aaed25d335
Revises: 73d78a4f6eb2
Create Date: 2022-10-27 09:19:34.534370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72aaed25d335'
down_revision = '73d78a4f6eb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('re_att_just', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket', 're_att_just')
    # ### end Alembic commands ###
