"""empty message

Revision ID: 73d78a4f6eb2
Revises: 
Create Date: 2022-10-27 08:02:51.127886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73d78a4f6eb2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('procedimento',
    sa.Column('_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('procedimento', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_table('user',
    sa.Column('_id', sa.String(), nullable=False),
    sa.Column('file', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('dep', sa.String(), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_table('ticket',
    sa.Column('_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('problema', sa.String(), nullable=False),
    sa.Column('ativo', sa.String(), nullable=False),
    sa.Column('prioridade', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('data_hora_a', sa.DateTime(), nullable=False),
    sa.Column('data_hora_f', sa.DateTime(), nullable=False),
    sa.Column('periodo', sa.String(), nullable=True),
    sa.Column('file', sa.String(), nullable=True),
    sa.Column('autor', sa.String(), nullable=False),
    sa.Column('att', sa.String(), nullable=True),
    sa.Column('dep', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user._id'], ),
    sa.PrimaryKeyConstraint('_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket')
    op.drop_table('user')
    op.drop_table('procedimento')
    # ### end Alembic commands ###
