"""empty message

Revision ID: ab10a47afb4e
Revises: 2b66bbf3ccf6
Create Date: 2024-06-03 10:27:36.256326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab10a47afb4e'
down_revision = '2b66bbf3ccf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('filtro', schema=None) as batch_op:
        batch_op.add_column(sa.Column('list_tooltips', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('filtro', schema=None) as batch_op:
        batch_op.drop_column('list_tooltips')

    # ### end Alembic commands ###
