"""empty message

Revision ID: cf21a4f2575c
Revises: 30374c9cc0a3
Create Date: 2024-06-13 16:43:16.863656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf21a4f2575c'
down_revision = '30374c9cc0a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('perfil', schema=None) as batch_op:
        batch_op.add_column(sa.Column('view_perfis', sa.Boolean(), nullable=True))
        batch_op.drop_column('create_perfil')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allow', sa.Boolean(), nullable=True))
        batch_op.drop_column('perfil')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('perfil', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('allow')

    with op.batch_alter_table('perfil', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_perfil', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('view_perfis')

    # ### end Alembic commands ###
