"""empty message

Revision ID: d2e206eff2bb
Revises: f55182ad5b55
Create Date: 2024-05-22 16:57:15.868667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2e206eff2bb'
down_revision = 'f55182ad5b55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dados',
    sa.Column('_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome_do_banco', sa.String(), nullable=False),
    sa.Column('coluna', sa.String(), nullable=False),
    sa.Column('descrição', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dados')
    # ### end Alembic commands ###
